WIP - DRAFT - Fix merge strategy for NSG/Subnet and remove usage of ID for NSG secl…
oracle/cluster-api-provider-oci pull request #114
Opened 2022-07-07 09:03 UTC by shyamradhakrishnan

Fix merge strategy for NSG/Subnet and remove usage of ID for NSG seclist reconciliation

**What this PR does / why we need it**:

* NSG/Subnet lists are hitting the issue mentioned https://main.cluster-api.sigs.k8s.io/developer/providers/v1.1-to-v1.2.html#required-api-changes-for-providers . Fix is as per the suggestion in the doc
* NSG Security rules has a similar problem but cant be fixed in a similar way because ID is generated and hence cannot be used in ClusterClass Server side patching. The ClusterClass template will not have the ID. Also, ideally, the NSG Seclist rules should just be  based on the actual rule comparison and not ID comparison. So we have changed code to use rule comparison.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #113

2022-07-07 13:24 UTC, joekr approved these changes

2022-07-07 13:35 UTC, shyamradhakrishnan commented on api/v1beta1/types.go
> +	// Deprecated: this field is not populated and used during reconciliation
not that I know of, I think we may never be able to remove this. I think that should be ok

2022-07-07 13:39 UTC, shyamradhakrishnan commented on api/v1beta1/types.go
> -	// +optional
the chances are very low, we typically have provided names for subnets in our templates and always sets it in the templates.

2022-07-07 13:42 UTC, shyamradhakrishnan commented on api/v1beta1/types.go
> -	// +optional
also if name is nil, we definitely would have failed reconciliation as we lookup using name and also use it for comparison

2022-07-07 13:44 UTC, joekr submitted a review, later dismissed

2022-07-08 12:08 UTC, joekr requested changes

2022-07-08 12:08 UTC, joekr commented on templates/cluster-template-cluster-class.yaml
> +        - id: ocid1.subnet.oc1.phx.aaaaaaaa7gyvlsu2vxtpiydb5iu5vg3v3cdb63ayavalabcidbh3sjilm5qq
Should we be setting the id here?

2022-07-08 12:08 UTC, joekr commented on templates/clusterclass-example.yaml
> +      compartmentId: ocid1.compartment.oc1..aaaaaaaaq6ucotbu72r32xznh5fnh2f77vfk2i35lwazp7gazk6lkzluvwqa
Should we be using the id here?

2022-07-08 12:22 UTC, closed without merging