Add doc for burstable instances
oracle/cluster-api-provider-oci pull request #169
Opened 2022-09-22 15:48 UTC by shyamradhakrishnan

**What this PR does / why we need it**:

Add doc for burstable instances

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

2022-09-22 19:24 UTC, joekr requested changes

2022-09-22 19:24 UTC, joekr commented on docs/src/gs/customize-worker-node.md
> +The following values are supported for baselineOcpuUtilization
```suggestion
The following values are supported for `baselineOcpuUtilization`
```

2022-09-23 03:48 UTC, shyamradhakrishnan commented on docs/src/gs/customize-worker-node.md
> +The following values are supported for baselineOcpuUtilization
fixed

2022-09-23 04:23 UTC, joekr approved these changes

2022-09-23 11:21 UTC, merged