Add DRG based VCN peering
oracle/cluster-api-provider-oci pull request #54
Opened 2022-04-07 04:11 UTC by shyamradhakrishnan

**What this PR does / why we need it**:
This PR add DRG based VCN peering to CAPOCI

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #14

2022-04-07 06:37 UTC, shyamradhakrishnan commented
Unit test
```
?   	github.com/oracle/cluster-api-provider-oci	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/api/v1beta1	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/config	[no test files]
ok  	github.com/oracle/cluster-api-provider-oci/cloud/ociutil	0.478s	coverage: 30.3% of statements
ok  	github.com/oracle/cluster-api-provider-oci/cloud/scope	176.808s	coverage: 81.9% of statements
?   	github.com/oracle/cluster-api-provider-oci/cloud/scope/mocks	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/compute	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/compute/mock_compute	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/identity	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/identity/mock_identity	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/networkloadbalancer	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/networkloadbalancer/mock_nlb	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/vcn	[no test files]
?   	github.com/oracle/cluster-api-provider-oci/cloud/services/vcn/mock_vcn	[no test files]
ok  	github.com/oracle/cluster-api-provider-oci/controllers	26.764s	coverage: 70.3% of statements
```

2022-04-11 15:12 UTC, joekr requested changes

2022-04-11 15:12 UTC, joekr commented on templates/cluster-template-local-vcn-peering.yaml
> +  replicas: ${WORKER_MACHINE_COUNT}
Should this be `NODE_MACHINE_COUNT`?

2022-04-11 15:15 UTC, joekr commented on cloud/scope/cluster.go
> +	ClientProvider        *ClientProvider
I think I understand the way. `ClientProvider` is used for the peering region while the `VCNClient` is used for the "current" region

2022-04-13 09:46 UTC, shyamradhakrishnan commented on cloud/scope/cluster.go
> +	ClientProvider        *ClientProvider
yes, I did not want to touch any code as that would be slightly risky and will need to change a whole lot of unit tests. WE need to use the clients like Normal for the Clusters region and only use the ClientProvider in special cases like the VCN peering thing. Makes sense?

2022-04-13 09:47 UTC, shyamradhakrishnan commented on cloud/scope/drg_reconciler.go
> +	return fmt.Sprintf("%s", s.OCICluster.Name)
The general consensus was that we should not add -<type> for anything, for example our VCN name, subnet name etc dont have the type appended.

2022-04-13 09:48 UTC, shyamradhakrishnan commented on cloud/scope/drg_rpc_attachment_reconciler.go
> +			err := wait.PollWithContext(ctx, PollInterval, RequestTimeout, func(ctx context.Context) (done bool, err error) {
This is different from RPC provisioning, this is connection and the API we use as well as the states are different. Does that make sense?

2022-04-13 09:55 UTC, shyamradhakrishnan commented on templates/cluster-template-local-vcn-peering.yaml
> +  replicas: ${WORKER_MACHINE_COUNT}
Done

2022-04-13 09:55 UTC, shyamradhakrishnan commented on controllers/ocicluster_controller_test.go
> +		recorder = record.NewFakeRecorder(20)
This is the number of events which will be stored in the fake recorder.

2022-04-13 09:55 UTC, shyamradhakrishnan commented on cloud/scope/drg_reconciler.go
> +	if s.OCICluster.Spec.NetworkSpec.VCNPeering.DRG == nil {
Done, please check if the change what I have done makes sense

2022-04-13 10:17 UTC, shyamradhakrishnan commented on cloud/scope/drg_rpc_attachment_reconciler.go
> +		}
The states are available, terminating, terminated and available. I think we should wait for it to reach terminated, it it does not reach the loop will timeout and the reconciliation will error out. Dees that sound ok?

2022-04-13 10:27 UTC, shyamradhakrishnan commented on cloud/scope/drg_vcn_attachment_reconciler.go
> +		return nil, errors.New("found more than one DRG VCN attachment to same VCN")
I have added more help in the error, is that ok? This is one of the corner cases where the api returns a list and 99% of times, users wont touch anything but we still need to handle the code.

2022-04-13 13:16 UTC, joekr commented on cloud/scope/drg_reconciler.go
> +// 2. Listing the Drgs for the Compartment (by ID) and filtering by tag
I love this kind of method comment and how it explains the high level steps! 😻

2022-04-13 13:26 UTC, joekr submitted a review, later dismissed

2022-04-14 12:19 UTC, joekr approved these changes

2022-04-14 12:24 UTC, merged